services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - CC_TEST_REPORTER_ID=5cbf4c9e6b9ff9cf049d26a2c85c3fbb5eb4cfbeae2d54ab549567bf567bdda6
    - PG_PORT=5433

language: node_js

node_js: 
  - "stable"

install:
  - npm install

cache:
  directories:
    - "node_modules"

after_success: npm run coverage
